image: docker:latest

variables:
  dirName: "./SayNoToDesignerExample/bin/Debug/net6.0-windows/1LAB_SECOND_PART_RUNTIME.exe"
  dirNameArtif: "./artifacts/"
  dirscript: "./main/test.sh"

build_job1:
  variables:
    testPath: "https://gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/browse"
  stage: build
  script:
    # тут переменная с путем сохраняется чтоб ее можно было использовать в другой job'е
    - echo "savePath=$testPath" >> build.env
    - echo "$savePath"
    - mkdir $dirNameArtif
    - cp $dirName $dirNameArtif 
  artifacts:
      paths:
        - $dirNameArtif/
      reports:
        dotenv: build.env

deploy_job1:
  stage: deploy
  script:
    - apk update
    - apk add bash
    - apk add curl
    - apk add jq
    - echo "$savePath"
    - chmod +x "$dirscript"
    - "$dirscript $savePath"
  dependencies:
    - build_job1

